package com.notification.entity;

public enum NotificationType {
    TICKET_CREATED,
    TICKET_ASSIGNED,
    TICKET_STATUS_CHANGED,
    TICKET_RESOLVED,
    TICKET_CLOSED,
    COMMENT_ADDED,
    SLA_WARNING,
    TICKET_ESCALATED,
    SLA_BREACH,
    TICKET_REASSIGNED,
    TICKET_UPDATED
}
